### ISSUE TITLE
`SITE_ID` should not be a required setting.

### ISSUE THREAD

**Issue by mrmachine** [edoburu/django-fluent-blogs#11]
Django no longer includes `SITE_ID` in the default `settings.py` and no longer adds `django.contrib.sites` to `INSTALLED_APPS`.

If it is actually required by `fluent-blogs`, adding `django.contrib.sites` to `INSTALLED_APPS` and defining `SITE_ID` should be mentioned in `README.rst`.

A quick search of the source reveals that this might also impact `fluent-contents` and `fluent-pages`. But for `fluent-blogs` it causes any management command to crash with a traceback.

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 70, in handle_noargs
    get_models()
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/db/models/loading.py", line 232, in get_models
    self._populate()
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/tailee/Projects/django-fluent-blogs/fluent_blogs/models/__init__.py", line 1, in <module>
    from .db import Entry, Entry_Translation, get_entry_model, get_category_model
  File "/Users/tailee/Projects/django-fluent-blogs/fluent_blogs/models/db.py", line 5, in <module>
    from fluent_blogs.base_models import CommentsEntryMixin, AbstractTranslatableEntry, AbstractTranslatedFieldsEntry
  File "/Users/tailee/Projects/django-fluent-blogs/fluent_blogs/base_models.py", line 9, in <module>
    from fluent_blogs.models.managers import EntryManager, TranslatableEntryManager
  File "/Users/tailee/Projects/django-fluent-blogs/fluent_blogs/models/managers.py", line 8, in <module>
    from fluent_blogs import appsettings
  File "/Users/tailee/Projects/django-fluent-blogs/fluent_blogs/appsettings.py", line 65, in <module>
    if len(FLUENT_BLOGS_LANGUAGES.get(settings.SITE_ID, ())) > 1:
  File "/Users/tailee/.virtualenvs/fluent-demo/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'SITE_ID'
```

That crash is an easy fix with `getattr(settings, 'SITE_ID, None)`, but I see that `SITE_ID` is also used elsewhere in the `fluents-blog` source.

**Comment by vdboor** [comment]
The appsettings code is fixed in d158ec0f618a1cd96f5d5f70b01061115cdf8a33, which can become part of v1.0.1. By defaut, the code now filters in SITE_ID to support multisite support. You can disable that with `FLUENT_BLOGS_FILTER_SITE_ID = False` in the settings. If you still have issues, a pull request is more then welcome!
