### ISSUE TITLE
TemplateSyntaxError at /admin/fluent_pages/page/add/

### ISSUE THREAD

**Issue by jjmontesl** [edoburu/django-fluent-blogs#17]
After creating a project following the [Getting Started](TemplateSyntaxError at /admin/fluent_pages/page/add/) tutorial, I am trying to create a page of type "Blog module" or to create a blog entry.

I see:

> TemplateSyntaxError at /admin/fluent_pages/page/add/
> Cannot read {{ block.super }} for {% block staff_toolbar %}, the parent template doesn't have this block.

The exception is:

```
[14/May/2016 21:41:09] "POST /admin/fluent_pages/page/add/ HTTP/1.1" 302 0
ERROR:	Internal Server Error: /admin/fluent_pages/page/add/
Traceback (most recent call last):
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/polymorphic/admin.py", line 258, in add_view
    return real_admin.add_view(request, form_url, extra_context)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1393, in changeform_view
    formsets, inline_instances = self._create_formsets(request, form.instance, change=False)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1718, in _create_formsets
    for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 697, in get_formsets_with_inlines
    for inline in self.get_inline_instances(request, obj):
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/fluent_contents/admin/placeholdereditor.py", line 188, in get_inline_instances
    inlinetypes = self.get_extra_inlines()
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/fluent_contents/admin/placeholdereditor.py", line 200, in get_extra_inlines
    return [self.placeholder_inline] + get_content_item_inlines(plugins=self.get_all_allowed_plugins())
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/fluent_pages/integration/fluent_contents/admin.py", line 86, in get_all_allowed_plugins
    slots = [placeholder.slot for placeholder in get_template_placeholder_data(template)]
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/fluent_contents/analyzer.py", line 24, in get_template_placeholder_data
    nodes = get_node_instances(template, PagePlaceholderNode)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 243, in get_node_instances
    return _scan_nodes(nodelist, context, instances)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 158, in _scan_nodes
    results += _extend_nodelist(node, context, instance_types)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 114, in _extend_nodelist
    results += _scan_nodes(block.nodelist, context, instance_types, block, ignore_blocks=all_block_names)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 167, in _scan_nodes
    current_block.name
TemplateSyntaxError: Cannot read {{ block.super }} for {% block staff_toolbar %}, the parent template doesn't have this block.
Internal Server Error: /admin/fluent_pages/page/add/
Traceback (most recent call last):
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/polymorphic/admin.py", line 258, in add_view
    return real_admin.add_view(request, form_url, extra_context)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1393, in changeform_view
    formsets, inline_instances = self._create_formsets(request, form.instance, change=False)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1718, in _create_formsets
    for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 697, in get_formsets_with_inlines
    for inline in self.get_inline_instances(request, obj):
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/fluent_contents/admin/placeholdereditor.py", line 188, in get_inline_instances
    inlinetypes = self.get_extra_inlines()
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/fluent_contents/admin/placeholdereditor.py", line 200, in get_extra_inlines
    return [self.placeholder_inline] + get_content_item_inlines(plugins=self.get_all_allowed_plugins())
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/fluent_pages/integration/fluent_contents/admin.py", line 86, in get_all_allowed_plugins
    slots = [placeholder.slot for placeholder in get_template_placeholder_data(template)]
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/fluent_contents/analyzer.py", line 24, in get_template_placeholder_data
    nodes = get_node_instances(template, PagePlaceholderNode)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 243, in get_node_instances
    return _scan_nodes(nodelist, context, instances)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 158, in _scan_nodes
    results += _extend_nodelist(node, context, instance_types)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 114, in _extend_nodelist
    results += _scan_nodes(block.nodelist, context, instance_types, block, ignore_blocks=all_block_names)
  File "/home/jjmontes/git/cubesviewer-server/x/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 167, in _scan_nodes
    current_block.name
TemplateSyntaxError: Cannot read {{ block.super }} for {% block staff_toolbar %}, the parent template doesn't have this block.
[14/May/2016 21:41:09] "GET /admin/fluent_pages/page/add/?ct_id=9 HTTP/1.1" 500 185825

```

**Comment by vdboor** [comment]
Hi, thanks for reporting this!

This turned out to be a bug in the project-template.
When you remove the staff-toolbar code from `frontend/templates/fluent_blogs/entry_archive_index.html` the page creation will work. 

You can also remove the template completely, although you may want to keep it to add some custom layouts for the blog index. ;-)
